server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
zuul:
  prefix: /api # 添加路由前缀
  routes:
    leyou-item-service: /item/**
    leyou-search: /search/**
    leyou-upload: #配置去除前缀
      path: /upload/**
      service-id: leyou-upload
      strip-prefix: false
    leyou-user-service: /user/**
    leyou-auth-service: /auth/**
    leyou-cart: /cart/**
    leyou-order: /order/**
  add-host-header: true #配置请求时将request的host添加到zuul的代理路径中
  sensitive-headers: #配置只忽略Set-Cookie Authorization两个敏感头，cookie不忽略
#  - Set-Cookie
#  - Authorization
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
#  OkToRetryOnAllOperations: false # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 50000 # 熔断超时时长：10000ms
            
leyou:
  jwt:
    pubKeyPath: E:\\rsa.pub # 公钥地址
    cookieName: LEYOU_TOKEN
  filter:
    allowPaths: #白名单，允许访问的路径
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item