server:
  port: 8083
  
spring:
  application:
    name: leyou-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.200.129:9300
  jackson:
    default-property-inclusion: non-null #配置jack装换json时为null的字段就不装换了
  rabbitmq:
    host: 192.168.200.129
    username: leyou
    password: leyou
    virtual-host: /leyou
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 #配置获取其他微服务的周期  5秒获取一次
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    
