server:
  port: 10086
  
spring:
  application:
    name: leyou-register

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: false #不向wureka注册自己
    fetch-registry: false #不从eureka拉取服务